--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: chaojiwudi.com
  external_host: ec2-50-18-73-28.us-west-1.compute.amazonaws.com
  external_ip: 50.18.73.28
  image_id: ami-cba1fe8e
  image_type: m1.large
  instance_id: i-7e529c38
  internal_host: ip-10-174-179-12.us-west-1.compute.internal
  internal_ip: 10.174.179.12
  name: qa0
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  root_device_type: ebs
  security_groups: 
  - default
  zone: us-west-1a
- volumes: {}

  static_ips: {}

