--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: chaojiwudi.com
  external_host: ec2-184-169-253-170.us-west-1.compute.amazonaws.com
  external_ip: 184.169.253.170
  image_id: ami-cba1fe8e
  image_type: m1.large
  instance_id: i-1cfe305a
  internal_host: ip-10-174-177-117.us-west-1.compute.internal
  internal_ip: 10.174.177.117
  name: qa
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  root_device_type: ebs
  security_groups: 
  - default
  - web
  zone: us-west-1a
- volumes: {}

  static_ips: {}

